### ISSUE TITLE
server log 错误

### ISSUE THREAD

**Issue by guisense** [tianshiyeben/wgcloud#17]
打开server 端的日志后，里面一直重复再报这个错误，
环境：CentOS 7.5
版本： wgcloud-v3.0

**server log:**

2020-06-04 17:06:39.510 [taskScheduler-29] INFO  com.wgcloud.task.ScheduledTask - 批量提交监控数据任务开始----------2020-06-04 17:06:39
2020-06-04 17:06:39.628 [taskScheduler-29] INFO  com.wgcloud.task.ScheduledTask - 批量提交监控数据任务结束----------2020-06-04 17:06:39
2020-06-04 17:06:54.932 [http-nio-9999-exec-1] INFO  com.wgcloud.filter.AuthRestFilter - uri----http://172.17.202.174:9999/wgcloud/agentGo/minTask
2020-06-04 17:07:18.975 [http-nio-9999-exec-9] INFO  com.wgcloud.filter.AuthRestFilter - uri----http://172.17.202.174:9999/wgcloud/agentGo/minTask
2020-06-04 17:07:18.977 [http-nio-9999-exec-9] ERROR o.a.c.c.C.[.[.[/wgcloud].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/wgcloud] threw exception [Request processing failed; nested exception is cn.hutool.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]] with root cause
cn.hutool.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:373)
	at cn.hutool.json.JSONArray.init(JSONArray.java:598)
	at cn.hutool.json.JSONArray.init(JSONArray.java:587)
	at cn.hutool.json.JSONArray.init(JSONArray.java:562)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:154)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:135)
	at cn.hutool.json.JSONGetter.getJSONArray(JSONGetter.java:63)
	at com.wgcloud.controller.AgentGoController.minTask(AgentGoController.java:75)
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.wgcloud.filter.AuthRestFilter.doFilter(AuthRestFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-06-04 17:07:29.509 [taskScheduler-40] INFO  com.wgcloud.task.ScheduledTask - heathMonitorTask------------2020-06-04 17:07:29
2020-06-04 17:07:35.945 [http-nio-9999-exec-5] INFO  com.wgcloud.filter.AuthRestFilter - uri----http://172.17.202.174:9999/wgcloud/agentGo/minTask
2020-06-04 17:07:36.920 [http-nio-9999-exec-8] INFO  com.wgcloud.filter.AuthRestFilter - uri----http://172.17.202.174:9999/wgcloud/appInfo/agentList
2020-06-04 17:07:36.947 [http-nio-9999-exec-6] INFO  com.wgcloud.filter.AuthRestFilter - uri----http://172.17.202.174:9999/wgcloud/dockerInfo/agentList

**Comment by tianshiyeben** [comment]
agent是不是有多个主机，每个系统都不一样

**Comment by tianshiyeben** [comment]
我重现问题了，你重新下载下安装包，试试就好了。
