### ISSUE TITLE
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: net/sf/jsqlparser/expression/Alias

### ISSUE THREAD

**Issue by pi408637535** [tianshiyeben/wgcloud#2]
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: net/sf/jsqlparser/expression/Alias
	at com.github.pagehelper.parser.CountSqlParser.<clinit>(CountSqlParser.java:137)
	at com.github.pagehelper.PageHelper.setProperties(PageHelper.java:134)
	at com.github.pagehelper.PageInterceptor.setProperties(PageInterceptor.java:172)
	at com.github.pagehelper.PageInterceptor.checkDialectExists(PageInterceptor.java:125)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:89)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy41.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy18.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy19.selectAllByParams(Unknown Source)
	at com.core.timer.impl.MonitorDayJobImpl.timingTask(MonitorDayJobImpl.java:73)
	at com.core.timer.impl.MonitorDayJobImpl.run(MonitorDayJobImpl.java:48)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: net.sf.jsqlparser.expression.Alias
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 24 more

及时我加了依赖,也不行，不知道什么该如何处理
 <dependency>
			  <groupId>net.sf.jsqlparser</groupId>
			  <artifactId>jsqlparser</artifactId>
			  <version>0.8.0</version>
		  </dependency>

**Comment by sunsulei** [comment]
https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#515---2018-09-02
搜索 `jsqlparser`

**Comment by tianshiyeben** [comment]
你试试把maven包清空，然后重新下载。可能是你jar没有下载完整。
