### ISSUE TITLE
为什么我下载的agent源码，无法直接用idea运行，并且打包后运行jar提示没有主清单属性，能否给解答下

### ISSUE THREAD

**Issue by qqbbddpp** [tianshiyeben/wgcloud#56]

**Comment by tianshiyeben** [comment]
不会啊，没碰到过这个问题，你IDEA运行时正常的吗



Good Luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 晚上9:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 为什么我下载的agent源码，无法直接用idea运行，并且打包后运行jar提示没有主清单属性，能否给解答下 (Issue #56)

**Comment by qqbbddpp** [comment]
server端是正常的，就是配套agent端不可以，版本是最新的，附件是我遇到的idea报错。

















在 2022-09-14 21:58:20，"tianshiyeben" ***@***.***> 写道：

不会啊，没碰到过这个问题，你IDEA运行时正常的吗



Good Luck


WGCLOUD


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tianshiyeben/wgcloud" ***@***.***&gt;;
发送时间:&nbsp;2022年9月14日(星期三) 晚上9:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tianshiyeben/wgcloud] 为什么我下载的agent源码，无法直接用idea运行，并且打包后运行jar提示没有主清单属性，能否给解答下 (Issue #56)






—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
"C:\Program Files\Java\jdk1.8.0_151\bin\java.exe" -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=57448 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:D:\IntelliJ IDEA 2018.1.6\lib\idea_rt.jar=57449:D:\IntelliJ IDEA 2018.1.6\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_151\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\rt.jar;E:\kaifa\wgcloudnew\wgcloud\wgcloud-agent\target\classes;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-starter-web\2.6.6\spring-boot-starter-web-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-starter\2.6.6\spring-boot-starter-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-starter-logging\2.6.6\spring-boot-starter-logging-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\ch\qos\logback\logback-classic\1.2.11\logback-classic-1.2.11.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\ch\qos\logback\logback-core\1.2.11\logback-core-1.2.11.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\logging\log4j\log4j-to-slf4j\2.17.2\log4j-to-slf4j-2.17.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\yaml\snakeyaml\1.29\snakeyaml-1.29.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-starter-json\2.6.6\spring-boot-starter-json-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\core\jackson-databind\2.13.2.2\jackson-databind-2.13.2.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\core\jackson-annotations\2.13.2\jackson-annotations-2.13.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\core\jackson-core\2.13.2\jackson-core-2.13.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.2\jackson-datatype-jdk8-2.13.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.2\jackson-datatype-jsr310-2.13.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.2\jackson-module-parameter-names-2.13.2.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-starter-tomcat\2.6.6\spring-boot-starter-tomcat-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\tomcat\embed\tomcat-embed-core\9.0.60\tomcat-embed-core-9.0.60.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\tomcat\embed\tomcat-embed-el\9.0.60\tomcat-embed-el-9.0.60.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.60\tomcat-embed-websocket-9.0.60.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-web\5.3.18\spring-web-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-beans\5.3.18\spring-beans-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-webmvc\5.3.18\spring-webmvc-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-aop\5.3.18\spring-aop-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-expression\5.3.18\spring-expression-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\projectlombok\lombok\1.18.22\lombok-1.18.22.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\cn\hutool\hutool-all\4.4.5\hutool-all-4.4.5.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\com\github\oshi\oshi-core\5.3.6\oshi-core-5.3.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\net\java\dev\jna\jna\5.10.0\jna-5.10.0.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\net\java\dev\jna\jna-platform\5.10.0\jna-platform-5.10.0.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-devtools\2.6.6\spring-boot-devtools-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot-autoconfigure\2.6.6\spring-boot-autoconfigure-2.6.6.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\boot\spring-boot\2.5.3\spring-boot-2.5.3.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-core\5.3.18\spring-core-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-jcl\5.3.18\spring-jcl-5.3.18.jar;E:\kaifa\wgcloudnew\wgcloud\yilai\org\springframework\spring-context\5.3.18\spring-context-5.3.18.jar" com.wgcloud.WgcloudServiceApplication
21:59:30.817 [Thread-1] DEBUG org.springframework.boot.devtools.restart.classloader.RestartClassLoader - Created RestartClassLoader ***@***.***

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.3)

2022-09-14 21:59:31.863  INFO 25888 --- [  restartedMain] com.wgcloud.WgcloudServiceApplication    : Starting WgcloudServiceApplication using Java 1.8.0_151 on LAPTOP-64UNQMU5 with PID 25888 (E:\kaifa\wgcloudnew\wgcloud\wgcloud-agent\target\classes started by 70986 in E:\kaifa\wgcloudnew\wgcloud\wgcloud-agent)
2022-09-14 21:59:31.865  INFO 25888 --- [  restartedMain] com.wgcloud.WgcloudServiceApplication    : No active profile set, falling back to default profiles: default
2022-09-14 21:59:31.961  INFO 25888 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-09-14 21:59:31.962  INFO 25888 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-09-14 21:59:33.187  WARN 25888 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.springframework.boot.web.servlet.server.CookieSameSiteSupplier not present
2022-09-14 21:59:33.210  INFO 25888 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-14 21:59:33.265 ERROR 25888 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.springframework.boot.web.servlet.server.CookieSameSiteSupplier not present
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.wgcloud.WgcloudServiceApplication.main(WgcloudServiceApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.springframework.boot.web.servlet.server.CookieSameSiteSupplier not present
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:217)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.springframework.boot.web.servlet.server.CookieSameSiteSupplier not present
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:671)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getWebServerFactoryCustomizerBeans(WebServerFactoryCustomizerBeanPostProcessor.java:87)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getCustomizers(WebServerFactoryCustomizerBeanPostProcessor.java:78)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:70)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	... 21 common frames omitted
Caused by: java.lang.TypeNotPresentException: Type org.springframework.boot.web.servlet.server.CookieSameSiteSupplier not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94)
	at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283)
	at java.lang.reflect.Method.getGenericParameterTypes(Method.java:283)
	at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:513)
	at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:291)
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:107)
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1421)
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1342)
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1324)
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1291)
	at org.springframework.beans.factory.config.DependencyDescriptor.getResolvableType(DependencyDescriptor.java:314)
	at org.springframework.beans.factory.support.GenericTypeAwareAutowireCandidateResolver.checkGenericTypeMatch(GenericTypeAwareAutowireCandidateResolver.java:77)
	at org.springframework.beans.factory.support.GenericTypeAwareAutowireCandidateResolver.isAutowireCandidate(GenericTypeAwareAutowireCandidateResolver.java:69)
	at org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver.isAutowireCandidate(QualifierAnnotationAutowireCandidateResolver.java:146)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.isAutowireCandidate(DefaultListableBeanFactory.java:862)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.isAutowireCandidate(DefaultListableBeanFactory.java:821)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.isAutowireCandidate(DefaultListableBeanFactory.java:804)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.web.servlet.server.CookieSameSiteSupplier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 65 common frames omitted


Process finished with exit code 0
